version: "3.9"

services:
  fastapi:
    build:
      context: .
      dockerfile: ./src/Dockerfile  # Ensure this matches your Dockerfile's name
    ports:
      - "8000:8000"  # Map FastAPI port
    volumes:
      - .:/app  # Mount current directory into the container
    environment:
      - PYTHONUNBUFFERED=1  # Optional: Ensures logs are printed in real time
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]  # Start FastAPI
